# Generated by Django 4.1.4 on 2023-01-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victorina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
        migrations.AddField(
            model_name='person',
            name='game_in_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='game_in_online',
            field=models.BooleanField(default=False),
        ),
    ]
